package Parse;

action code {: static Symbol.Symbol sym(String s) {
	         return Symbol.Symbol.symbol(s);
	        }
	    :};

parser code  {: 
  Lexer lexer;

  public void syntax_error(java_cup.runtime.Symbol current) {
   report_error("Syntax error (" + current.sym + ")", current);
  }

  ErrorMsg.ErrorMsg errorMsg;

  public void report_error(String message, java_cup.runtime.Symbol info) {
      errorMsg.error(info.left, message);
  }

  public Grm(Lexer l, ErrorMsg.ErrorMsg err) {
    this();
    errorMsg=err;
    lexer=l;
  }
:};

scan with {: return lexer.nextToken(); :};



terminal String ID, STRING;
terminal Integer INT;
terminal COMMA, COLON, SEMICOLON, LPAREN, RPAREN, LBRACK, RBRACK, 
	LBRACE, RBRACE, DOT, PLUS, MINUS, TIMES, DIVIDE, EQ, NEQ, LT, LE, 
	GT, GE, AND, OR, ASSIGN, ARRAY, IF, THEN, ELSE, WHILE, FOR, TO,
	DO, LET, IN, END, OF, BREAK, NIL, FUNCTION, VAR, TYPE;

  /*C tokents added for 3.3.2*/
  terminal ARROW, INCR, DECR;

  /*C tokents for 3.3.3*/
  terminal SIZEOF, AMP, TILDE, BANG;
  /*temp stand in for type name*/
  terminal TYPENAME;

  /*C token for 3.3.5*/
  terminal MOD;
/*C tokent for 3.3.7*/
  terminal LSHIFT, RSHIFT;

  /*C tokens added for 3.3.11-3.3.14*/
  terminal CARET, PIPE, ANDAND, OROR;

  /* tokens for 3.3.15-3.3.16*/
  terminal QUESTION;
  terminal EQUALS, MUL_ASSIGN, DIV_ASSIGN, MOD_ASSIGN, ADD_ASSIGN, SUB_ASSIGN, 
          LSHIFT_ASSIGN, RSHIFT_ASSIGN, AND_ASSIGN, XOR_ASSIGN, OR_ASSIGN;

/*3.6.1*/
terminal CASE, DEFAULT;

/* C token 3.6.4*/
terminal SWITCH;
terminal LOWER_THAN_ELSE;

/* token for 3.6.6*/
terminal GOTO, CONTINUE, RETURN;

/*temp need to be taken out later*/




non terminal Absyn.Exp          Exp;
non terminal Absyn.Var          Var;

/* c grammor from c89*/
non terminal primary_expression;
non terminal postfix_expression;
non terminal argument_expression_list;
non terminal unary_expression;
non terminal unary_operator;
non terminal cast_expression;
non terminal multiplication_expression;
non terminal additive_exression;
non terminal shift_expression;
non terminal relational_expression;
non terminal equality_expression;
non terminal and_expression;
non terminal exclusive_or_expression;
non terminal inclusive_or_expression;
non terminal logical_and_expression;
non terminal logical_or_expression;
non terminal conditional_expression;
non terminal constant_expression;
non terminal assignment_operator;
non terminal assignment_expression;
non terminal expression;
non terminal type_name;
non terminal statement;
non terminal labeled_statement;
non terminal compound_statement;
non terminal declaration_list;
non terminal statement_list;
non terminal declatation;
non terminal expression_statement;
non terminal selection_statement;
non terminal iteration_statement;
non terminal jump_statement;


precedence nonassoc LOWER_THAN_ELSE;
precedence nonassoc ELSE;

start with Exp;

Exp ::= error:e
	  {: RESULT = new Absyn.SeqExp(eleft, null); :}
	| Var:v
	  {: RESULT = new Absyn.VarExp(vleft, v); :}
	;

Var ::=   ID:n
	  {: RESULT = new Absyn.SimpleVar(nleft, sym(n)); :}
	;


/*3.3.1 primary expressions*/
primary_expression ::=
  ID  /* identifier*/
 |INT /* constant*/
 | STRING /* string literal*/
 | LPAREN expression RPAREN
  ;


/*3.3.2 postfix*/
postfix_expression ::=
  primary_expression
|  postfix_expression LBRACK expression RBRACK
|  postfix_expression LPAREN RPAREN
|  postfix_expression LPAREN argument_expression_list RPAREN
|  postfix_expression DOT ID
|  postfix_expression ARROW ID
|  postfix_expression INCR
|  postfix_expression DECR
  ;

argument_expression_list ::=
  assignment_expression
 | argument_expression_list COMMA assignment_expression
  ;


/* 3.3.3 unary operatiors*/
unary_expression ::=
  postfix_expression
  | INCR unary_expression
  | DECR unary_expression
  | unary_operator cast_expression
  | SIZEOF LPAREN type_name RPAREN
  ;

unary_operator ::=
  AMP 
  | TIMES
  | PLUS
  | MINUS 
  | TILDE
  | BANG
  ;

/*3.3.4*/
cast_expression ::=
  unary_expression
  ;


/*3.3.5*/
multiplication_expression ::= 
  cast_expression
  | multiplication_expression TIMES cast_expression
  | multiplication_expression DIVIDE cast_expression
  | multiplication_expression MOD cast_expression
  ;

/*3.3.6 additive_exression*/
additive_exression ::=
  multiplication_expression
  | additive_exression PLUS multiplication_expression
  | additive_exression MINUS multiplication_expression
  ;

/*3.3.7 bwise shift*/
shift_expression ::=
   additive_exression
  | shift_expression LSHIFT additive_exression
  | shift_expression RSHIFT additive_exression
  ;


/* 3.3.8 relaiton operatiors*/
relational_expression ::= 
  shift_expression
  | relational_expression LT shift_expression
  | relational_expression GT shift_expression
  | relational_expression LE shift_expression
  | relational_expression GE shift_expression
  ;

/*3.3.9 equality operatiors*/
equality_expression ::=
  relational_expression
  | equality_expression EQ relational_expression
  | equality_expression NEQ relational_expression
  ;

/*3.3.10 bwise and */
and_expression ::= 
  equality_expression
  | and_expression AMP equality_expression
  ;

/*3.3.11 bwise exclusice or operator*/
exclusive_or_expression ::=
  and_expression
  | exclusive_or_expression CARET and_expression
  ;

/*3.3.12 logical and operatiors*/
inclusive_or_expression ::=
  exclusive_or_expression
  | inclusive_or_expression PIPE exclusive_or_expression
  ;


/*3.3.13 logical and operator*/
logical_and_expression ::=
  inclusive_or_expression
  | logical_and_expression ANDAND inclusive_or_expression
  ;

/*3.3.14 logical or */
logical_or_expression ::=
  logical_and_expression
  | logical_or_expression OROR logical_and_expression
  ;

/*3.3.15 conditional operatiors*/
conditional_expression ::=
  logical_or_expression
  | logical_or_expression QUESTION expression COLON conditional_expression
  ;

 /*3.3.16 assign ment operatiors*/
 assignment_expression ::=
    conditional_expression
    | unary_expression assignment_operator assignment_expression
    ; 

assignment_operator ::=
  EQUALS 
  | MUL_ASSIGN
  | DIV_ASSIGN 
  | MOD_ASSIGN
  | ADD_ASSIGN
  | SUB_ASSIGN
  | LSHIFT_ASSIGN
  | RSHIFT_ASSIGN
  | AND_ASSIGN
  | XOR_ASSIGN
  | OR_ASSIGN
  ;

/*3.3.17 comma */
expression ::= 
  assignment_expression
  | expression COMMA assignment_expression
  ;



/*3.3.4 constant expressions*/
 constant_expression ::=
    conditional_expression
    ;


/* 3.6 statements*/
statement ::=
  labeled_statement
  | compound_statement
  | expression_statement
  | selection_statement
  | iteration_statement
  | jump_statement
  ;


/*3.6.1 labled statementts*/
labeled_statement ::=
  ID COLON statement
  | CASE constant_expression COLON statement
  | DEFAULT COLON statement
  ;


/*3.6.2 compound statemetn or block*/
compound_statement ::=
  LBRACE declaration_list statement_list RBRACE
  | LBRACE declaration_list RBRACE
  | LBRACE statement_list RBRACE
  | LBRACE RBRACE
  ;

declaration_list ::=
  declatation
  | declaration_list declatation
  ;

statement_list ::=
  statement
  | statement_list statement
  ;
  
/*3.6.3 expression and null */
expression_statement ::=
  expression SEMICOLON
  | SEMICOLON
  ;


/*3.6.4 selection statemetn*/
selection_statement ::=
  IF LPAREN expression RPAREN statement %prec LOWER_THAN_ELSE
  | IF LPAREN expression RPAREN statement ELSE statement
  | SWITCH LPAREN expression RPAREN statement
  ;

/* 3.6.5 iteration statements*/

iteration_statement ::=
	  WHILE LPAREN expression RPAREN statement
	| DO statement WHILE LPAREN expression RPAREN SEMICOLON
	| FOR LPAREN expression SEMICOLON expression SEMICOLON expression RPAREN statement
	| FOR LPAREN expression SEMICOLON expression SEMICOLON            RPAREN statement
	| FOR LPAREN expression SEMICOLON            SEMICOLON expression RPAREN statement
	| FOR LPAREN expression SEMICOLON            SEMICOLON            RPAREN statement
	| FOR LPAREN            SEMICOLON expression SEMICOLON expression RPAREN statement
	| FOR LPAREN            SEMICOLON expression SEMICOLON            RPAREN statement
	| FOR LPAREN            SEMICOLON            SEMICOLON expression RPAREN statement
	| FOR LPAREN            SEMICOLON            SEMICOLON            RPAREN statement
	;

jump_statement ::=
  GOTO ID SEMICOLON
  | CONTINUE SEMICOLON
  | BREAK SEMICOLON
  | RETURN expression SEMICOLON
  |RETURN SEMICOLON
  ;



  /* place holders needs to be taken out later*/


  type_name ::= TYPENAME
  ;