
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Mon Oct 05 11:36:21 CDT 2026
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int TIMES = 17;
  static final int MOD_ASSIGN = 64;
  static final int GT = 23;
  static final int ARROW = 45;
  static final int AMP = 49;
  static final int TYPE = 44;
  static final int SUB_ASSIGN = 66;
  static final int GE = 24;
  static final int INCR = 46;
  static final int RBRACK = 11;
  static final int SIZEOF = 48;
  static final int COMMA = 5;
  static final int RBRACE = 13;
  static final int RPAREN = 9;
  static final int AND_ASSIGN = 69;
  static final int LBRACK = 10;
  static final int LT = 21;
  static final int ANDAND = 58;
  static final int OROR = 59;
  static final int LBRACE = 12;
  static final int LPAREN = 8;
  static final int TILDE = 50;
  static final int RSHIFT_ASSIGN = 68;
  static final int LE = 22;
  static final int NIL = 41;
  static final int ARRAY = 28;
  static final int DECR = 47;
  static final int XOR_ASSIGN = 70;
  static final int VAR = 43;
  static final int THEN = 30;
  static final int EQ = 19;
  static final int MOD = 53;
  static final int PIPE = 57;
  static final int ADD_ASSIGN = 65;
  static final int PLUS = 15;
  static final int DIVIDE = 18;
  static final int QUESTION = 60;
  static final int WHILE = 32;
  static final int MUL_ASSIGN = 62;
  static final int ASSIGN = 27;
  static final int DO = 35;
  static final int FOR = 33;
  static final int ELSE = 31;
  static final int BREAK = 40;
  static final int DOT = 14;
  static final int INT = 4;
  static final int EOF = 0;
  static final int SEMICOLON = 7;
  static final int BANG = 51;
  static final int FUNCTION = 42;
  static final int MINUS = 16;
  static final int IN = 37;
  static final int OR = 26;
  static final int error = 1;
  static final int OR_ASSIGN = 71;
  static final int IF = 29;
  static final int LSHIFT_ASSIGN = 67;
  static final int ID = 2;
  static final int DIV_ASSIGN = 63;
  static final int OF = 39;
  static final int END = 38;
  static final int COLON = 6;
  static final int CARET = 56;
  static final int TYPENAME = 52;
  static final int RSHIFT = 55;
  static final int STRING = 3;
  static final int NEQ = 20;
  static final int AND = 25;
  static final int TO = 34;
  static final int LSHIFT = 54;
  static final int LET = 36;
  static final int EQUALS = 61;

  /* non terminals */
  static final int multiplication_expression = 9;
  static final int primary_expression = 3;
  static final int assignment_expression = 22;
  static final int Var = 2;
  static final int cast_expression = 8;
  static final int unary_expression = 6;
  static final int and_expression = 14;
  static final int conditional_expression = 19;
  static final int $START = 0;
  static final int shift_expression = 11;
  static final int postfix_expression = 4;
  static final int exclusive_or_expression = 15;
  static final int expression = 23;
  static final int inclusive_or_expression = 16;
  static final int logical_and_expression = 17;
  static final int relational_expression = 12;
  static final int equality_expression = 13;
  static final int Exp = 1;
  static final int logical_or_expression = 18;
  static final int constant_expression = 20;
  static final int argument_expression_list = 5;
  static final int additive_exression = 10;
  static final int unary_operator = 7;
  static final int type_name = 24;
  static final int assignment_operator = 21;
}

